# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  name: nix-modules
  description: Collection of custom-made modules for NixOS
  topics: nix, nixos, gitops
  private: true
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: latest
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: latest
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
      restrictions: null
