# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.alejandra]
command = 'alejandra'
includes = ['**.nix']

[formatter.prettier]
command = 'prettier'
includes = ['**.json', '**.yaml', '**.yml', '**/flake.lock']
options = ['--write']
